name: tkit
description: "Twitch Toolkit"
publish_to: "none"
version: 0.0.1-dev.8+1

environment:
  sdk: ^3.9.2

dependencies:
  sentry_flutter: ^9.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  equatable: ^2.0.7

  # Database
  drift: ^2.29.0
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1

  # HTTP & API
  dio: ^5.9.0
  json_annotation: ^4.9.0

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # Utilities
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  auto_route: ^11.0.0
  tray_manager: ^0.5.1
  local_notifier: ^0.1.6
  intl: ^0.20.2
  file_picker: ^10.3.7

  # Logging
  talker: ^5.1.2
  talker_flutter: ^5.1.2

  # Hotkeys
  hotkey_manager: ^0.2.3

  # Version info
  package_info_plus: ^9.0.0

  gpt_markdown: ^1.1.4
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3

  # Tutorial
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generators
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  drift_dev: ^2.30.0
  auto_route_generator: ^10.3.0

  # Testing
  mockito: ^5.6.1
  http_mock_adapter: ^0.6.1
  integration_test:
    sdk: flutter

  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

dependency_overrides:
  analyzer: ^8.4.1
  _fe_analyzer_shared: ^91.0.0
  source_gen: ^4.0.2
  characters: 1.4.1
  js: 0.7.2
  material_color_utilities: 0.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - Assets/Icon512x512.ico
    - Assets/Icon512x512.png

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: tkit
  org: evobug
